# Generated by Django 2.1.8 on 2019-04-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='titie',
            new_name='title',
        ),
    ]
